"""Declarative base shared by every ORM model.

The naming convention matters more than it looks: without it, Postgres
auto-names constraints (e.g. "papers_pmid_key"), Alembic can't reliably
reference them in autogenerated migrations, and DROP CONSTRAINT statements
break across environments. Explicit names make migrations deterministic.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDMixin:
    """UUID primary keys over auto-increment integers: safe to expose in URLs
    (no enumeration attacks — /papers/3 invites guessing /papers/4), and
    generatable client-side before the INSERT, which simplifies bulk ingestion."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    """server_default=func.now() puts the timestamp in Postgres's hands, not
    Python's — correct even for rows inserted by raw SQL or another service."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
