"""multi-source papers: dedup_key, source provenance, citations, doi

Adds the columns that let one `papers` table hold records from any of the ten
federated sources, deduplicated by a single canonical key. Written by hand (not
autogenerated) because existing rows must be backfilled: dedup_key is UNIQUE
NOT NULL, so we add it nullable, populate it from the pre-existing PMIDs, then
tighten the constraint.

Revision ID: a1b2c3d4e5f6
Revises: 28b144a528e5
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "28b144a528e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Add new columns, all nullable/defaulted so existing rows survive.
    op.add_column("papers", sa.Column("dedup_key", sa.String(length=300), nullable=True))
    op.add_column("papers", sa.Column("source", sa.String(length=40),
                                      nullable=False, server_default="pubmed"))
    op.add_column("papers", sa.Column("sources", sa.dialects.postgresql.JSONB(),
                                      nullable=False, server_default="[]"))
    op.add_column("papers", sa.Column("doi", sa.String(length=255), nullable=True))
    op.add_column("papers", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("papers", sa.Column("citation_count", sa.Integer(),
                                      nullable=False, server_default="0"))
    op.add_column("papers", sa.Column("url", sa.String(length=1000), nullable=True))
    op.add_column("papers", sa.Column("is_preprint", sa.Boolean(),
                                      nullable=False, server_default=sa.false()))

    # 2. Backfill existing PubMed rows: canonical key from PMID, provenance list.
    op.execute("UPDATE papers SET dedup_key = 'pmid:' || pmid WHERE dedup_key IS NULL")
    op.execute("""UPDATE papers SET sources = '["pubmed"]'::jsonb
                  WHERE sources = '[]'::jsonb""")

    # 3. Tighten: dedup_key becomes the unique identity; pmid becomes optional
    #    (most sources have no PMID).
    op.alter_column("papers", "dedup_key", nullable=False)
    op.create_index("ix_papers_dedup_key", "papers", ["dedup_key"], unique=True)
    op.create_index("ix_papers_doi", "papers", ["doi"])
    op.alter_column("papers", "pmid", existing_type=sa.String(length=20), nullable=True)


def downgrade() -> None:
    op.alter_column("papers", "pmid", existing_type=sa.String(length=20), nullable=False)
    op.drop_index("ix_papers_doi", table_name="papers")
    op.drop_index("ix_papers_dedup_key", table_name="papers")
    for col in ("is_preprint", "url", "citation_count", "external_id", "doi",
                "sources", "source", "dedup_key"):
        op.drop_column("papers", col)
